services:
  application:
    build: .
    depends_on:
      - redis
    environment:
      BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      FLASK_APP: src
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - .:/srv
  redis:
    image: redis:4-alpine
  mongo:
    image: mongo:4
version: "3.6"
