services:
  application:
    build: .
    environment:
      FLASK_APP: src
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
    ports:
      - 8080:8080
version: "3.6"
